# SPDX-License-Identifier: GPL-2.0

dtbo-$(CONFIG_BOARD_BANANAPI_CM7) += \
	bpi-cm7-i2c0.dtbo \
	bpi-cm7-i2c1.dtbo \
	bpi-cm7-ph10-ir.dtbo \
	bpi-cm7-uart3.dtbo \
	bpi-cm7-uart4.dtbo \
	bpi-cm7-uart5.dtbo \
	bpi-cm7-reserved.dtbo

targets += $(dtbo-y)
always	:= $(dtbo-y)
clean-files := *.dtbo
